# Generated by Django 4.2.7 on 2023-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duedate', models.DateField()),
                ('dead', models.BooleanField(default=False)),
            ],
        ),
    ]
